/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mathtutor;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.border.BevelBorder;

/**
 *
 * @author Eric Sullivan
 */
public class accountPanelForm extends javax.swing.JPanel {
    private String iconLabel;
    /**
     * Creates new form accountPanelForm
     */
    public accountPanelForm() {
        initComponents();
        
    }
    /**
     * constructor sets up panels
     * @param name
     * @param icon 
     */
    public accountPanelForm(String name,String icon){
        initComponents();
        this.Name.setText(name);
        this.iconLabel=icon;
        this.icon.setIcon(new ImageIcon(""+icon));
        setBackground(Color.GREEN);
        setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        
    }
    /**
     * gets Jlabel names test
     * @return Name
     */
    public String getJLabelName(){
        return Name.getText();
    }
    /**
     * gets JLabel icon
     * @return icon
     */
    public String getJLabelIcon(){
        return iconLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Name.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel icon;
    // End of variables declaration//GEN-END:variables
}
