/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mathtutor;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Eric Sullivan
 */
public class ModuleSelectorWindow extends javax.swing.JPanel {
    ArrayList<Module> modules;
    ModuleSelectorWindow layer;
    Login frame;
    /**
     * Creates new form ModuleSelectorWindow
     */
    public ModuleSelectorWindow() {
        initComponents();
    }
    public  ModuleSelectorWindow(String grade,Login frame){
        this.frame = frame;
        initComponents();
        layer = this;
        modules = new ArrayList<>();
        System.out.println(grade);
        if(grade.equals("Pre K - K")){
            modules.add(new Module("Coins","Coins"));
            modules.add(new Module("Compare","Compare"));
            modules.add(new Module("Counting","Counting"));
            modules.add(new Module("Estimate","Estimate"));
            modules.add(new Module("Numbers","Numbers"));
            modules.add(new Module("Problems","Problems"));
            modules.add(new Module("Sequences","Sequences"));
            modules.add(new Module("Whole","Whole"));
            
        }
        JPanel pane = new JPanel(new GridLayout(2,2,10,10));
        pane.setBackground(new Color(144,210,144));
        for(int i=0;i<modules.size();i++){
            modules.get(i).addMouseListener(new Listener());
            pane.add(modules.get(i));
            if (i % 4 == 3 && i != 0) {
                    System.out.println("added at " + i);
                    jPanel1.add(pane);
                    pane = new JPanel(new GridLayout(2,2,10,10));
                    pane.setBackground(new Color(144,210,144));
                }
        }
    }
        public class Listener extends MouseAdapter {
        public void mouseClicked(MouseEvent e){
            frame.remove(layer);
            frame.getLastPane().push(layer);
            frame.setCurrentPane( new TestGeneral(((Module)e.getSource()).getjLabel1().getText(),"",frame));
            frame.add(frame.getCurrentPane());
            frame.repaint();
            frame.pack();
            ;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(144, 210, 144));

        jPanel1.setBackground(new java.awt.Color(144, 210, 144));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
