/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mathtutor;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Eric Sullivan
 */
public class ModuleSelectorWindow extends javax.swing.JPanel {
    ArrayList<Module> modules;
    //ModuleSelectorWindow layer;
    Login frame;
    ModuleSelectorLayer layer;
    /**
     * Creates new form ModuleSelectorWindow
     */
    public ModuleSelectorWindow() {
        initComponents();
    }
    public  ModuleSelectorWindow(String grade,Login frame,ModuleSelectorLayer parent){
        this.frame = frame;
        initComponents();
        layer = parent;
        modules = new ArrayList<>();
        System.out.println(grade);
        next.addMouseListener(new NextPrev());
        prev.addMouseListener(new NextPrev());
        setPreferredSize(new Dimension(600,600));
        if(grade.equals("Pre K - K")){
            modules.add(new Module("Coins","Coins"));
            modules.add(new Module("Compare","Compare"));
            modules.add(new Module("Counting","Counting"));
            modules.add(new Module("Estimate","Estimate"));
            modules.add(new Module("Numbers","Numbers"));
            modules.add(new Module("Problems","Problems"));
            modules.add(new Module("Sequences","Sequences"));
            modules.add(new Module("Wholes","Wholes"));
            
        }
        JPanel pane = new JPanel(new GridLayout(2,2,10,10));
        pane.setBackground(new Color(144,210,144));
        for(int i=0;i<modules.size();i++){
            modules.get(i).addMouseListener(new Listener());
            pane.add(modules.get(i));
            if (i % 4 == 3 && i != 0) {
                    System.out.println("added at " + i);
                    jPanel1.add(pane);
                    pane = new JPanel(new GridLayout(2,2,10,10));
                    pane.setBackground(new Color(144,210,144));
                }
        }
    }
        public class Listener extends MouseAdapter {
        public void mouseClicked(MouseEvent e){
            frame.remove(layer);
            frame.getLastPane().push(layer);
            frame.setCurrentPane( new ToTLayer(((Module)e.getSource()).getjLabel1().getText(),"",frame));
            frame.add(frame.getCurrentPane());
            frame.repaint();
            frame.pack();
            ;
        }
    }
        public class NextPrev extends MouseAdapter {
            public void mouseClicked(MouseEvent e){
            if(e.getSource()==next){
               ((CardLayout)jPanel1.getLayout()).next(jPanel1);
            }
            if(e.getSource()==prev){
                ((CardLayout)jPanel1.getLayout()).previous(jPanel1);
            }
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        next = new javax.swing.JLabel();
        prev = new javax.swing.JLabel();

        setBackground(new java.awt.Color(144, 210, 144));

        jPanel1.setBackground(new java.awt.Color(144, 210, 144));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 50)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Course");

        next.setText("jLabel2");

        prev.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel next;
    private javax.swing.JLabel prev;
    // End of variables declaration//GEN-END:variables
}
