/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mathtutor;

import javax.swing.ImageIcon;

/**
 *
 * @author Eric Sullivan
 */
public class Reward extends PanelTemplate {

    /**
     * Creates new form Reward
     */
    public Reward(int correct) {
        initComponents();
        numCorrect.setText(""+correct+"/6 correct!");
        if(correct>=4){
            icon.setIcon(new ImageIcon("sun.png"));
        }
        else{
            icon.setIcon(new ImageIcon("frown.png"));
            banner.setText("Try Again!!");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        Module = new javax.swing.JLabel();
        numCorrect = new javax.swing.JLabel();
        seeWrongPane = new javax.swing.JPanel();
        seeWrong = new javax.swing.JLabel();
        print = new javax.swing.JLabel();

        setBackground(new java.awt.Color(144, 210, 144));

        banner.setFont(new java.awt.Font("Comic Sans MS", 1, 50)); // NOI18N
        banner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banner.setText("Congratulations");

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        icon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Module.setBackground(new java.awt.Color(144, 210, 144));
        Module.setFont(new java.awt.Font("Comic Sans MS", 1, 25)); // NOI18N
        Module.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Module.setText("Counting");
        Module.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        numCorrect.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        numCorrect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numCorrect.setText("Num correct");

        seeWrongPane.setBackground(new java.awt.Color(255, 150, 14));
        seeWrongPane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        seeWrong.setFont(new java.awt.Font("Comic Sans MS", 0, 25)); // NOI18N
        seeWrong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seeWrong.setText("See Wrong Answers");

        javax.swing.GroupLayout seeWrongPaneLayout = new javax.swing.GroupLayout(seeWrongPane);
        seeWrongPane.setLayout(seeWrongPaneLayout);
        seeWrongPaneLayout.setHorizontalGroup(
            seeWrongPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seeWrong, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        seeWrongPaneLayout.setVerticalGroup(
            seeWrongPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seeWrongPaneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(seeWrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        print.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        print.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print.setText("Print");
        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Module, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(numCorrect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seeWrongPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Module, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(seeWrongPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Module;
    private javax.swing.JLabel banner;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel numCorrect;
    private javax.swing.JLabel print;
    private javax.swing.JLabel seeWrong;
    private javax.swing.JPanel seeWrongPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public void help() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void back() {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
