/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mathtutor;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.GridLayout;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Eric Sullivan
 */
public class SeeWrongPane extends javax.swing.JPanel {
    ArrayList<testForm> test;
    ArrayList<testForm> wrongs;
    Login frame;
    SeeWrongPane here;
    /**
     * Creates new form SeeWrongPane
     */
    public SeeWrongPane() {
        initComponents();
        jPanel1.setLayout(new GridLayout(6,1));
    }
    public SeeWrongPane(ArrayList<testForm> test,Login frame) {
        initComponents();
        wrongs = new ArrayList<>();
        this.test = test;
        this.frame = frame;
        here = this;
        jPanel1.setLayout(new GridLayout(6, 1,10,10));
        populate();
    }
    public void populate() {
        for(int i = 0; i<6;i++){
            if(test.get(i).isCorrect()==0){
                WrongAnswer temp = new WrongAnswer(""+test.get(i).getNumber());
                temp.setCursor(new Cursor(Cursor.HAND_CURSOR));
                temp.addMouseListener(new Listener());
                wrongs.add(test.get(i));
                jPanel1.add(temp);
            }
        }
    }
    public class Listener extends MouseAdapter {
        
        public void mouseClicked(MouseEvent e) {
            System.out.println(((WrongAnswer)e.getSource()).getjLabel1().getText());
            String temp = ((WrongAnswer)e.getSource()).getjLabel1().getText();
            String[] split = temp.split(" ");
            testForm current = test.get(Integer.parseInt(split[1])-1);
            frame.remove(here);
            frame.getLastPane().push(here);
            frame.setCurrentPane(new wrongForm(current,frame));
            frame.add(frame.getCurrentPane());
            frame.repaint();
            frame.pack();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(144, 210, 144));
        setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 50)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wrong Answers");

        jPanel1.setBackground(new java.awt.Color(144, 210, 144));
        jPanel1.setPreferredSize(new java.awt.Dimension(470, 470));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
