/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathtutor;

import javax.swing.ImageIcon;

/**
 *
 * @author
 */
public class UserCustomization extends javax.swing.JPanel {

    /**
     * Creates new form UserCustomization
     */
    private Account account;
    public UserCustomization(Account account) {
        initComponents();
        this.account = account;
        initLabels();
        loadModuleIconsFromDB();
    }
    private void loadModuleIconsFromDB()
    {
       DataBaseUserConnector con = new DataBaseUserConnector("MathTutorDB", "TutorAdmin", "Tut0r4dm1n");
       byte[] bStickers = con.getStickersForUser(account);
       for(int i = 0; i < bStickers.length; ++i)
           System.out.println(bStickers[i]);
           System.out.println(jlTFOne.getName());
       con.closeDBConnection();
    }
    //private static final int ICON_HEIGHT = 100;
    //private static final int ICON_WIDTH = 100;
    private void initLabels()
    {
        //Make sure to display correct user icon later
        //jlabelUserIcon.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlabelUserIcon.setIcon(account.getIcon());
        
        //jlTFOne.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlTFOne.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        jlTFOne.setName("jlTFOne");
       // jlTFTwo.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlTFTwo.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlTFThree.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlTFThree.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlTFFour.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlTFFour.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlTFFive.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlTFFive.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlTFSix.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlTFSix.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlTFSeven.setSize(ICON_HEIGHT, ICON_WIDTH);
        jlTFSeven.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlOTOne.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlOTOne.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlOTTwo.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlOTTwo.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlOTThree.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlOTThree.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlOTFour.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlOTFour.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlOTFive.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlOTFive.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlOTSix.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlOTSix.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlOTSeven.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlOTSeven.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlOTEight.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlOTEight.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlPKOne.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlPKOne.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlPKTwo.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlPKTwo.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlPKThree.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlPKThree.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlPKFour.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlPKFour.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlPKFive.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlPKFive.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlPKSix.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlPKSix.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlPKSeven.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlPKSeven.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        //jlPKEight.setSize(ICON_HEIGHT,ICON_WIDTH);
        jlPKEight.setIcon(new ImageIcon(".\\Icons\\Icons\\icons\\lock.png"));
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlabelUserIcon = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlTFOne = new javax.swing.JLabel();
        jlTFTwo = new javax.swing.JLabel();
        jlTFThree = new javax.swing.JLabel();
        jlTFFour = new javax.swing.JLabel();
        jlTFFive = new javax.swing.JLabel();
        jlTFSix = new javax.swing.JLabel();
        jlTFSeven = new javax.swing.JLabel();
        jlTFEight = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jlOTOne = new javax.swing.JLabel();
        jlOTTwo = new javax.swing.JLabel();
        jlOTThree = new javax.swing.JLabel();
        jlOTFour = new javax.swing.JLabel();
        jlOTFive = new javax.swing.JLabel();
        jlOTSix = new javax.swing.JLabel();
        jlOTSeven = new javax.swing.JLabel();
        jlOTEight = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jlPKOne = new javax.swing.JLabel();
        jlPKTwo = new javax.swing.JLabel();
        jlPKThree = new javax.swing.JLabel();
        jlPKFour = new javax.swing.JLabel();
        jlPKFive = new javax.swing.JLabel();
        jlPKSix = new javax.swing.JLabel();
        jlPKSeven = new javax.swing.JLabel();
        jlPKEight = new javax.swing.JLabel();

        setBackground(new java.awt.Color(144, 210, 144));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setFont(new java.awt.Font("Stencil Std", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Profile Icon");

        jlabelUserIcon.setText(" ");

        jLabel10.setFont(new java.awt.Font("Stencil Std", 1, 38)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Grade 3-4 Awards");

        jlTFOne.setToolTipText("");

        jlTFFive.setToolTipText("");

        jLabel22.setFont(new java.awt.Font("Stencil Std", 1, 38)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Grade 1-2 Awards");

        jlOTSix.setToolTipText("");

        jLabel34.setFont(new java.awt.Font("Stencil Std", 1, 38)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Pre K - K Awards");

        jlPKOne.setToolTipText("");

        jlPKTwo.setToolTipText("");

        jlPKThree.setToolTipText("");

        jlPKFour.setToolTipText("");

        jlPKFive.setToolTipText("");

        jlPKSix.setToolTipText("");

        jlPKSeven.setToolTipText("");

        jlPKEight.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jlabelUserIcon)
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlTFOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlTFTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlTFThree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlTFFour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlTFFive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlTFSix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlTFSeven)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlTFEight))
                    .addComponent(jLabel22)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlOTOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlOTTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlOTThree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlOTFour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlOTFive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlOTSix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlOTSeven)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlOTEight))
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlPKOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlPKTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlPKThree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlPKFour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlPKFive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlPKSix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlPKSeven)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlPKEight)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jlabelUserIcon)
                .addGap(0, 0, 0)
                .addComponent(jLabel10)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTFOne)
                    .addComponent(jlTFTwo)
                    .addComponent(jlTFThree)
                    .addComponent(jlTFFour)
                    .addComponent(jlTFFive)
                    .addComponent(jlTFSix)
                    .addComponent(jlTFSeven)
                    .addComponent(jlTFEight))
                .addGap(0, 0, 0)
                .addComponent(jLabel22)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlOTOne)
                    .addComponent(jlOTTwo)
                    .addComponent(jlOTThree)
                    .addComponent(jlOTFour)
                    .addComponent(jlOTFive)
                    .addComponent(jlOTSix)
                    .addComponent(jlOTSeven)
                    .addComponent(jlOTEight))
                .addGap(0, 0, 0)
                .addComponent(jLabel34)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPKOne)
                    .addComponent(jlPKTwo)
                    .addComponent(jlPKThree)
                    .addComponent(jlPKFour)
                    .addComponent(jlPKFive)
                    .addComponent(jlPKSix)
                    .addComponent(jlPKSeven)
                    .addComponent(jlPKEight))
                .addContainerGap(397, Short.MAX_VALUE))
        );

        jlabelUserIcon.getAccessibleContext().setAccessibleName("jlUserIcon");
        jlPKFour.getAccessibleContext().setAccessibleName("jlPKFive");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jlOTEight;
    private javax.swing.JLabel jlOTFive;
    private javax.swing.JLabel jlOTFour;
    private javax.swing.JLabel jlOTOne;
    private javax.swing.JLabel jlOTSeven;
    private javax.swing.JLabel jlOTSix;
    private javax.swing.JLabel jlOTThree;
    private javax.swing.JLabel jlOTTwo;
    private javax.swing.JLabel jlPKEight;
    private javax.swing.JLabel jlPKFive;
    private javax.swing.JLabel jlPKFour;
    private javax.swing.JLabel jlPKOne;
    private javax.swing.JLabel jlPKSeven;
    private javax.swing.JLabel jlPKSix;
    private javax.swing.JLabel jlPKThree;
    private javax.swing.JLabel jlPKTwo;
    private javax.swing.JLabel jlTFEight;
    private javax.swing.JLabel jlTFFive;
    private javax.swing.JLabel jlTFFour;
    private javax.swing.JLabel jlTFOne;
    private javax.swing.JLabel jlTFSeven;
    private javax.swing.JLabel jlTFSix;
    private javax.swing.JLabel jlTFThree;
    private javax.swing.JLabel jlTFTwo;
    private javax.swing.JLabel jlabelUserIcon;
    // End of variables declaration//GEN-END:variables
}
